language: generic
sudo: required

env:
  - ARCH=i486 RELEASE=3.0.2.8

services:
  - docker

before_install:
  - docker build --build-arg "ARCH=$ARCH" --build-arg "RELEASE=$RELEASE" -t baseimage-build .

script:
  - echo "Done!"
