language: generic
sudo: required

env:
  - ARCH=i486 RELEASE=3.0.2.8

services:
  - docker

before_install:
  - docker pull coderus/sailfishos-baaseimage
  - docker run --rm --privileged --network=host -v $(pwd):/share -w /share
    mic create fs
    -v
    -d
    --arch=$ARCH
    --outdir=/share
    --tokenmap=ARCH:$ARCH,RELEASE:$RELEASE
    --record-pkgs=url,name,license
    --pack-to=@NAME@.tar.bz2
    baseimage.ks

script:
  - echo "Done!"
