name: Github CI build

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  ARCH: i486
  RELEASE: 4.5.0.16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: System info
      run: |
        df -i
        df -h
        docker info
    - name: Clear up some space on runner
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Prepare
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      run: echo "RELEASE=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build tarballs
      run: docker run --rm --privileged --network=host -v $(pwd):/share -w /share coderus/sailfishos-baseimage
            mic create fs
            -v
            -d
            --arch=$ARCH
            --outdir=/share
            --tokenmap=ARCH:$ARCH,RELEASE:$RELEASE
            --pack-to=baseimage.tar
            baseimage.ks

    - name: Setup base
      run: |
        set -x
        docker import baseimage.tar coderus/sailfishos-baseimage:latest
        docker tag coderus/sailfishos-baseimage:latest coderus/sailfishos-baseimage:$RELEASE
        docker push coderus/sailfishos-baseimage:latest
        docker push coderus/sailfishos-baseimage:$RELEASE